// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6pbsC7lTFRVAo9WH8xr04EDqVfC0S7Ko',
    appId: '1:645199450837:web:25cdfcbb2a63a06c97085c',
    messagingSenderId: '645199450837',
    projectId: 'dating-app-cda12',
    authDomain: 'dating-app-cda12.firebaseapp.com',
    storageBucket: 'dating-app-cda12.appspot.com',
    measurementId: 'G-9W2BK018KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcUqEHSngDT25VJLCryLqjuECzWAMwaIY',
    appId: '1:645199450837:android:84e24b584db1c51997085c',
    messagingSenderId: '645199450837',
    projectId: 'dating-app-cda12',
    storageBucket: 'dating-app-cda12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUPjqktpXAXl1lFvY3W1EqLT-po74ApLE',
    appId: '1:645199450837:ios:6209a5646873408997085c',
    messagingSenderId: '645199450837',
    projectId: 'dating-app-cda12',
    storageBucket: 'dating-app-cda12.appspot.com',
    iosClientId: '645199450837-n21ai1q9nur6fovbdcecj54v8hbi4eb5.apps.googleusercontent.com',
    iosBundleId: 'com.webster-dating-app.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUPjqktpXAXl1lFvY3W1EqLT-po74ApLE',
    appId: '1:645199450837:ios:2a2308f1fb823b6697085c',
    messagingSenderId: '645199450837',
    projectId: 'dating-app-cda12',
    storageBucket: 'dating-app-cda12.appspot.com',
    iosClientId: '645199450837-ga922a3ipm7heq26e11i5s9qcf4m3r0t.apps.googleusercontent.com',
    iosBundleId: 'com.webster-dating-app.datingApp.RunnerTests',
  );
}
